In [1]:
import random

lista = list(range(10))
random.shuffle(lista)
print(lista)

[6, 1, 7, 9, 4, 0, 2, 8, 3, 5]


In [37]:
import torch as tr

x = tr.tensor(
    [
        [
            [1, 0, 0, 0, 0],
            [0, 0, 1, 0, 0],
            [0, 0, 0, 1, 0],
            [0, 1, 0, 0, 1],
        ]
    ]
)
x.shape

torch.Size([1, 4, 5])

In [1]:
import random

import torch as tr

x = tr.tensor(
    [
        [1, 0, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 1, 0, 0, 1],
    ]
)
x.shape

x_l = [_ for _ in range(x.shape[-1])]
random.shuffle(x_l)
v = [0, 1, 2, 3]

x2 = x
print(x2)
N = 2
for s in range(N):
    nt = x_l[-1]
    x_l.pop()
    random.shuffle(v)
    val = tr.zeros([4], dtype=tr.float)
    val[v[0]] = 1.0
    x[:, nt] = val
print(x2)

tensor([[1, 0, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 1, 0, 0, 1]])
tensor([[1, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]])


In [2]:
def noise(x, N=0):
    assert N < x.shape[-1], "N should be lower than the shape of x (starting on 0)"
    x_l = [_ for _ in range(x.shape[-1])]
    random.shuffle(x_l)
    v = [0, 1, 2, 3]

    for _ in range(N):
        pos = x_l[-1]
        x_l.pop()
        random.shuffle(v)
        nt = tr.zeros([4], dtype=tr.float)
        nt[v[0]] = 1.0
        x[:, pos] = nt
    return x

In [3]:
x = tr.tensor(
    [
        [1, 0, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 1, 0, 0, 1],
    ]
)
print(x.shape)

x = noise(x, N=4)
print(x)

torch.Size([4, 5])
tensor([[0, 0, 1, 1, 1],
        [1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0]])


In [5]:
import torch as tr

def add_noise(x, n_swaps=0): 

    if n_swaps == 0:
        return x

    if n_swaps > x.shape[-1]:
        n_swaps = x.shape[-1]
        
    x_l = [_ for _ in range(x.shape[-1])]
    random.shuffle(x_l)
    v = [0, 1, 2, 3]

    for i in range(n_swaps): 
        nt = tr.zeros([4], dtype=tr.float)
        random.shuffle(v)
        nt[v[0]] = 1.0
        x[:, x_l[i]] = nt
    return x


In [2]:
import torch as tr 
import random
from typing import Union

x = tr.tensor(
    [
        [1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 1],
    ]
)
 
def add_noise(x: tr.Tensor, swaps: Union[int,float] = 0, mode: str = 'perc') -> tr.Tensor:
    """
    Introduces noise into the tensor `x` by modifying some of its columns with random values.

    Parameters:
    x (torch.Tensor): Input tensor of size (N, len), where N=4 is the number of One-Hot dimension and len is the number of nucleotides.
    swaps (int or float, optional): Number of swaps to perform. Can be:
        - A positive integer, specifying the exact number of swaps.
        - A value between 0 and 1, interpreted as a percentage of the number of columns.
        - 0 (default), meaning no changes are made.
    mode (str, optional): Interpretation mode of `swaps`.
        - 'perc' (default): If `swaps` is 1, all columns are replaced.
        - 'int': `swaps` is treated as an absolute number of swaps.

    Returns:
    torch.Tensor: Modified tensor with added noise.
    """
    len = x.shape[-1]
    if swaps == 0:
        return x
    elif swaps > 0 and swaps < 1: 
        swaps = round(len * swaps)
    elif (mode == 'perc' and swaps == 1) or swaps > len:
        swaps = len
    
    rand_nt = [_ for _ in range(len)]
    random.shuffle(rand_nt)
    v = [0, 1, 2, 3] 
    
    for i in range(swaps): 
        nt = tr.zeros([4], dtype=tr.float)
        random.shuffle(v)
        nt[v[0]] = 1.0
        x[:, rand_nt[i]] = nt
    return x

print(x)  
add_noise(x, swaps=1, mode='perc')
print(x)

tensor([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 1]])
tensor([[1, 0, 0, 0, 0],
        [0, 0, 0, 1, 1],
        [0, 0, 1, 0, 0],
        [0, 1, 0, 0, 0]])


In [3]:
x.shape

torch.Size([4, 5])

In [9]:
x = tr.tensor(
    [
        [1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 1],
    ]
)
print(x)  
print(x.shape)  
print('++++++++++++++++++++++++++++++++++++')  

add_noise(x, swaps=0.2, mode='int')
print(x)

tensor([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 1]])
torch.Size([4, 5])
++++++++++++++++++++++++++++++++++++
tensor([[1, 0, 0, 0, 0],
        [0, 1, 0, 1, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 0, 1]])


In [91]:
x = tr.tensor(
    [
        [1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 1],
    ]
)
print(x) 
add_noise(x, swaps=1, mode='perc')
print(x)

tensor([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 1]])
n_swaps = 5
rand_nt = [3, 2, 0, 4, 1]
tensor([[0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [1, 1, 0, 1, 1],
        [0, 0, 0, 0, 0]])


In [ ]:
x = tr.tensor(
    [
        [1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 1],
    ]
)

print(x.shape)
print(x)

x = add_noise(x, swaps=2)
print(x)

torch.Size([4, 5])
tensor([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 1]])
tensor([[1, 1, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 1, 1, 1]])


In [1]:
l = [p/128 for p in range(129)]
for i in range(129):
    if (i %16 == 0):
        print(l[i])

0.0
0.125
0.25
0.375
0.5
0.625
0.75
0.875
1.0


In [ ]:
p=(0.0 0.125 0.25 0.375 0.5 0.625 0.75 0.875 1.0)

In [1]:
from src.seq2seq.metrics import compute_metrics


In [ ]:
import torch as tr
x = tr.tensor([[
    [1.,1.,1.,1.],
    [0.,0.,0.,0.],
    [0.,0.,0.,0.],
    [0.,0.,0.,0.],
]])
x.shape

torch.Size([1, 4, 4])

In [67]:
x.all()

tensor(False)

In [174]:
x = tr.tensor([
    [[1.,1.,1.,0.],
     [0.,0.,0.,0.],
     [0.,0.,0.,1.],],
    [[1.,0.,1.,1.],
     [0.,1.,0.,0.],
     [0.,0.,0.,0.],]
    ])
mask = tr.tensor([[True, True, True,False], 
                  [True, True, True,True],
                  ])
print(mask.shape)

print(x.shape)
xt = x.permute(0,2,1)
xt[mask]

torch.Size([2, 4])
torch.Size([2, 3, 4])


tensor([[1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [0., 1., 0.],
        [1., 0., 0.],
        [1., 0., 0.]])

In [175]:
(xt[mask] == xt_[mask] ).all(dim=1)

tensor([ True,  True,  True, False, False, False,  True])

In [176]:
x_ = tr.tensor([
    [[1.,1.,1.,0.],
     [0.,0.,0.,0.],
     [0.,0.,0.,1.],],
    [[0.,1.,0.,1.],
     [0.,0.,1.,0.],
     [1.,0.,0.,0.],]
    ])


print(x_.shape)
xt_ = x_.permute(0,2,1)


torch.Size([2, 3, 4])


In [177]:
xt_ = x_.permute(0,2,1)
xt = x.permute(0,2,1)
print(xt.shape, xt_.shape)
print(xt[mask].shape, xt_[mask].shape)
print(xt)
print(xt_[mask][2,:])
print( xt[mask][2,:])
(xt_ == xt).all(dim=1).all(dim=1).float().mean().item()


torch.Size([2, 4, 3]) torch.Size([2, 4, 3])
torch.Size([7, 3]) torch.Size([7, 3])
tensor([[[1., 0., 0.],
         [1., 0., 0.],
         [1., 0., 0.],
         [0., 0., 1.]],

        [[1., 0., 0.],
         [0., 1., 0.],
         [1., 0., 0.],
         [1., 0., 0.]]])
tensor([1., 0., 0.])
tensor([1., 0., 0.])


0.5

In [94]:

def compute_metrics(x_rec, x_true, mask, output_th=0.5):
    xt_rec = (x_rec > output_th).permute(0,2,1)
    xt_true = x_true.permute(0,2,1)
    acc = (xt_rec[mask] == xt_true[mask]).all(dim=-1).float().mean().item()
    return acc

In [24]:
(x == x_).all(dim=-1).float().mean().item()

0.75

In [50]:
r = compute_metrics(x,x_,mask)
r

IndexError: boolean index did not match indexed array along axis 0; size of axis is 16 but size of corresponding boolean axis is 4

In [55]:
# Compara si el vector de cada paso coincide totalmente
match = (x == x_) | (mask)  # Ignora posiciones con padding
print(match)
match_per_step = match.all(dim=-1)         # [B, E] — True si el vector está completamente correcto o era padding
print(match_per_step)
# Elimina pasos que eran padding completo (i.e. todos los vocab_size con mask = 0)
valid_steps = mask.any(dim=-1)           # [B, E] — True si hay al menos una posición relevante
print(valid_steps)
accuracy = match_per_step[valid_steps].float().mean().item()
print(accuracy)

tensor([[[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]])
tensor([[True, True, True, True]])
tensor(True)
1.0


In [147]:
print(xt)
# print(xt_)

# Obtener el índice de la clase predicha y verdadera
pred_idx = xt.argmax(dim=-1)   # [B, L]
true_idx = xt_.argmax(dim=-1)  # [B, L]

print(pred_idx)
print(true_idx)
# Aplanar para simplificar
pred_flat = pred_idx[mask]   # solo donde mask == True
true_flat = true_idx[mask]

# print(pred_flat)
# print(true_flat)


# Métricas
TP = (pred_flat == true_flat).sum().item()
total = mask.sum().item()

accuracy = TP / total if total > 0 else 0.0

tensor([[[1., 0., 0.],
         [1., 0., 0.],
         [1., 0., 0.],
         [1., 0., 0.]],

        [[1., 0., 0.],
         [0., 1., 0.],
         [1., 0., 0.],
         [1., 0., 0.]]])
tensor([[0, 0, 0, 0],
        [0, 1, 0, 0]])
tensor([[0, 0, 0, 2],
        [2, 0, 1, 0]])


In [5]:
import pandas as pd
from torch.utils.data import Dataset
import torch as tr
import os
import json
import pickle
import random
from src.seq2seq.embeddings import OneHotEmbedding
from typing import Union



class SeqDataset(Dataset):
    def __init__(
        self,
        dataset_path,
        min_len=0,
        max_len=512,
        verbose=False,
        cache_path=None,
        for_prediction=False,
        training=False,
        swaps=0,
        mode='perc',
        **kargs,
    ):
        """
        interaction_prior: none, probmat
        """
        self.max_len = max_len
        self.verbose = verbose
        if cache_path is not None and not os.path.isdir(cache_path):
            os.mkdir(cache_path)
        self.cache = cache_path

        # Loading dataset
        data = pd.read_csv(dataset_path)
        self.training = training

        assert (
            "sequence" in data.columns and "id" in data.columns
        ), "Dataset should contain 'id' and 'sequence' columns"

        data["len"] = data.sequence.str.len()

        if max_len is None:
            max_len = max(data.len)
        self.max_len = max_len

        datalen = len(data)

        data = data[(data.len >= min_len) & (data.len <= max_len)]

        if len(data) < datalen:
            print(
                f"From {datalen} sequences, filtering {min_len} < len < {max_len} we have {len(data)} sequences"
            )

        self.sequences = data.sequence.tolist()
        self.ids = data.id.tolist()
        self.embedding = OneHotEmbedding()
        self.embedding_size = self.embedding.emb_size
        self.swaps = swaps
        self.mode = mode
        

    def __len__(self):
        return len(self.sequences)

    def __getitem__(self, idx):
        seqid = self.ids[idx]
        cache = f"{self.cache}/{seqid}.pk"
        if (self.cache is not None) and os.path.isfile(cache):
            item = pickle.load(open(cache, "rb"))
        else:
            sequence = self.sequences[idx]
            L = len(sequence)
            seq_emb = self.embedding.seq2emb(sequence)
            if self.swaps == 0:
                embedding_with_noise = seq_emb
            elif self.swaps != 0:
                embedding_with_noise = add_noise(seq_emb.clone(), self.swaps)
            else:
                print('ERROR: swaps < 0')

            item = {
                "id": seqid,
                "length": L,
                "sequence": sequence,
                "embedding": seq_emb,
                "embedding_with_noise": embedding_with_noise,
            }

            if self.cache is not None:
                pickle.dump(item, open(cache, "wb"))

        return item


def pad_batch(batch, fixed_length=0):
    """batch is a dictionary with different variables lists"""
    L = [b["length"] for b in batch]
    if fixed_length == 0:
        fixed_length = max(L)
    embedding_pad = tr.zeros((len(batch), batch[0]["embedding"].shape[0], fixed_length))
    embedding_pad_w_noise = tr.zeros(
        (len(batch), batch[0]["embedding_with_noise"].shape[0], fixed_length)
    )
    mask = tr.zeros((len(batch), fixed_length), dtype=tr.bool)

    for k in range(len(batch)):
        embedding_pad[k, :, : L[k]] = batch[k]["embedding"]
        embedding_pad_w_noise[k, :, : L[k]] = batch[k]["embedding_with_noise"]
        mask[k, : L[k]] = 1

    out_batch = {
        "id": [b["id"] for b in batch],
        "length": L,
        "sequence": [b["sequence"] for b in batch],
        "embedding": embedding_pad,
        "embedding_with_noise": embedding_pad_w_noise,
        "mask": mask,
    }

    return out_batch


def add_noise(x: tr.Tensor, swaps: Union[int,float] = 0, mode: str = 'perc') -> tr.Tensor:
    """
    Introduces noise into the tensor `x` by modifying some of its columns with random values.

    Parameters:
    x (torch.Tensor): Input tensor of size (N, len), where N=4 is the number of One-Hot dimension and len is the number of nucleotides.
    swaps (int or float, optional): Number of swaps to perform. Can be:
        - A positive integer, specifying the exact number of swaps.
        - A value between 0 and 1, interpreted as a percentage of the number of columns.
        - 0 (default), meaning no changes are made.
    mode (str, optional): Interpretation mode of `swaps`.
        - 'perc' (default): If `swaps` is 1, all columns are replaced.
        - 'int': `swaps` is treated as an absolute number of swaps.

    Returns:
    torch.Tensor: Modified tensor with added noise.
    """
    len = x.shape[-1]
    if swaps == 0:
        return x
    elif swaps > 0 and swaps < 1: 
        swaps = round(len * swaps)
    elif (mode == 'perc' and swaps == 1) or swaps > len:
        swaps = len
    
    rand_nt = [_ for _ in range(len)]
    random.shuffle(rand_nt)
    v = [0, 1, 2, 3] 
    
    for i in range(swaps): 
        nt = tr.zeros([4], dtype=tr.float)
        random.shuffle(v)
        nt[v[0]] = 1.0
        x[:, rand_nt[i]] = nt
    return x


import torch as tr  


def compute_metrics(x_rec, x_true, mask):
    """
    Calculates the F1 score, accuracy (sequence level and threshold),
    precision, recall, and perplexity.

    Args:
        x_rec (torch.Tensor): Reconstructed sequence [N, C, L].
        x_true (torch.Tensor): True sequence [N, C, L]. 
        mask (torch.Tensor): Mask to filter valid sequences [N, C, L].

    Returns:
        dict: Calculated metrics.
    """
    xt_rec = x_rec.permute(0,2,1)
    xt_true = x_true.permute(0,2,1) 

    # Obtener el índice de la clase predicha y verdadera
    pred_idx = xt_rec.argmax(dim=-1)   # [B, L]
    true_idx = xt_true.argmax(dim=-1)  # [B, L]
 
    pred_flat = pred_idx[mask]    
    true_flat = true_idx[mask]
 
    TP = (pred_flat == true_flat).sum().item()    
    
    total = mask.sum().item()
    accuracy = TP / total if total > 0 else 0.0

    FP = FN = (pred_flat != true_flat).sum().item()
    precision = TP / (TP + FP) if (TP + FP) > 0 else 0.0
    recall    = TP / (TP + FN) if (TP + FN) > 0 else 0.0
    f1        = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0.0
 
    seq_accuracy = (x_rec == x_true).all(dim=1).all(dim=1).float().mean().item()

    # Devolver todas las métricas
    return {"F1": f1, "Accuracy": accuracy, "Accuracy_seq": seq_accuracy}


In [32]:
from functools import partial

pad_batch_with_fixed_length = partial(pad_batch, fixed_length=128)
dataset_path = '/home/gkulemeyer/Documents/Repos/AEseq2seq/data/ArchiveII-KFold/common/fold_0_test.csv'
data = SeqDataset( dataset_path, min_len=0, max_len=512, verbose=False, cache_path=None, for_prediction=False,  training=False, swaps=1)
from torch.utils.data import DataLoader

loader = DataLoader(data, batch_size=128, shuffle=False,collate_fn=pad_batch_with_fixed_length)

l = next(iter(loader))
l.keys()

dict_keys(['id', 'length', 'sequence', 'embedding', 'embedding_with_noise', 'mask'])

In [33]:
print(l['embedding'].shape)
print(l['embedding_with_noise'].shape)
print(l['mask'].shape)

torch.Size([128, 4, 128])
torch.Size([128, 4, 128])
torch.Size([128, 128])


In [34]:
compute_metrics(l['embedding'], l['embedding_with_noise'], l['mask'])

{'F1': 0.2523894630507421, 'Accuracy': 0.2523894630507421, 'Accuracy_seq': 0.0}

In [ ]:
compute_metrics(l)