In [1]:
import random

lista = list(range(10))
random.shuffle(lista)
print(lista)

[6, 1, 7, 9, 4, 0, 2, 8, 3, 5]


In [37]:
import torch as tr

x = tr.tensor(
    [
        [
            [1, 0, 0, 0, 0],
            [0, 0, 1, 0, 0],
            [0, 0, 0, 1, 0],
            [0, 1, 0, 0, 1],
        ]
    ]
)
x.shape

torch.Size([1, 4, 5])

In [1]:
import random

import torch as tr

x = tr.tensor(
    [
        [1, 0, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 1, 0, 0, 1],
    ]
)
x.shape

x_l = [_ for _ in range(x.shape[-1])]
random.shuffle(x_l)
v = [0, 1, 2, 3]

x2 = x
print(x2)
N = 2
for s in range(N):
    nt = x_l[-1]
    x_l.pop()
    random.shuffle(v)
    val = tr.zeros([4], dtype=tr.float)
    val[v[0]] = 1.0
    x[:, nt] = val
print(x2)

tensor([[1, 0, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 1, 0, 0, 1]])
tensor([[1, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]])


In [2]:
def noise(x, N=0):
    assert N < x.shape[-1], "N should be lower than the shape of x (starting on 0)"
    x_l = [_ for _ in range(x.shape[-1])]
    random.shuffle(x_l)
    v = [0, 1, 2, 3]

    for _ in range(N):
        pos = x_l[-1]
        x_l.pop()
        random.shuffle(v)
        nt = tr.zeros([4], dtype=tr.float)
        nt[v[0]] = 1.0
        x[:, pos] = nt
    return x

In [3]:
x = tr.tensor(
    [
        [1, 0, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 1, 0, 0, 1],
    ]
)
print(x.shape)

x = noise(x, N=4)
print(x)

torch.Size([4, 5])
tensor([[0, 0, 1, 1, 1],
        [1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0]])


In [5]:
import torch as tr

def add_noise(x, n_swaps=0): 

    if n_swaps == 0:
        return x

    if n_swaps > x.shape[-1]:
        n_swaps = x.shape[-1]
        
    x_l = [_ for _ in range(x.shape[-1])]
    random.shuffle(x_l)
    v = [0, 1, 2, 3]

    for i in range(n_swaps): 
        nt = tr.zeros([4], dtype=tr.float)
        random.shuffle(v)
        nt[v[0]] = 1.0
        x[:, x_l[i]] = nt
    return x


In [2]:
import torch as tr 
import random
from typing import Union

x = tr.tensor(
    [
        [1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 1],
    ]
)
 
def add_noise(x: tr.Tensor, swaps: Union[int,float] = 0, mode: str = 'perc') -> tr.Tensor:
    """
    Introduces noise into the tensor `x` by modifying some of its columns with random values.

    Parameters:
    x (torch.Tensor): Input tensor of size (N, len), where N=4 is the number of One-Hot dimension and len is the number of nucleotides.
    swaps (int or float, optional): Number of swaps to perform. Can be:
        - A positive integer, specifying the exact number of swaps.
        - A value between 0 and 1, interpreted as a percentage of the number of columns.
        - 0 (default), meaning no changes are made.
    mode (str, optional): Interpretation mode of `swaps`.
        - 'perc' (default): If `swaps` is 1, all columns are replaced.
        - 'int': `swaps` is treated as an absolute number of swaps.

    Returns:
    torch.Tensor: Modified tensor with added noise.
    """
    len = x.shape[-1]
    if swaps == 0:
        return x
    elif swaps > 0 and swaps < 1: 
        swaps = round(len * swaps)
    elif (mode == 'perc' and swaps == 1) or swaps > len:
        swaps = len
    
    rand_nt = [_ for _ in range(len)]
    random.shuffle(rand_nt)
    v = [0, 1, 2, 3] 
    
    for i in range(swaps): 
        nt = tr.zeros([4], dtype=tr.float)
        random.shuffle(v)
        nt[v[0]] = 1.0
        x[:, rand_nt[i]] = nt
    return x

print(x)  
add_noise(x, swaps=1, mode='perc')
print(x)

tensor([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 1]])
tensor([[1, 0, 0, 0, 0],
        [0, 0, 0, 1, 1],
        [0, 0, 1, 0, 0],
        [0, 1, 0, 0, 0]])


In [3]:
x.shape

torch.Size([4, 5])

In [9]:
x = tr.tensor(
    [
        [1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 1],
    ]
)
print(x)  
print(x.shape)  
print('++++++++++++++++++++++++++++++++++++')  

add_noise(x, swaps=0.2, mode='int')
print(x)

tensor([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 1]])
torch.Size([4, 5])
++++++++++++++++++++++++++++++++++++
tensor([[1, 0, 0, 0, 0],
        [0, 1, 0, 1, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 0, 1]])


In [91]:
x = tr.tensor(
    [
        [1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 1],
    ]
)
print(x) 
add_noise(x, swaps=1, mode='perc')
print(x)

tensor([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 1]])
n_swaps = 5
rand_nt = [3, 2, 0, 4, 1]
tensor([[0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [1, 1, 0, 1, 1],
        [0, 0, 0, 0, 0]])


In [ ]:
x = tr.tensor(
    [
        [1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 1],
    ]
)

print(x.shape)
print(x)

x = add_noise(x, swaps=2)
print(x)

torch.Size([4, 5])
tensor([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 1]])
tensor([[1, 1, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 1, 1, 1]])
